pkgname = "orm"
output = "db/orm"
wipe = true
add-global-variants = true
no-tests = false

[psql]
  dbname = "misskey"
  port = 3002
  user = "misskey"
  pass = ""
  schema = "public"
  blacklist = []
