pkgname = "models"
output = "models"
wipe = true
no-tests = false

[psql]
  dbname = "misskey"
  #host = "/usr/home/rand/dev/misskey/build/postgres/sock"
  port = 3002
  user = "misskey"
  pass = ""
  schema = "public"
  blacklist = []

