/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// ChannelsPinNote - channels/pin-note
func ChannelsPinNote(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// RequestResetPassword - request-reset-password
func RequestResetPassword(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ResetDb - reset-db
func ResetDb(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ResetPassword - reset-password
func ResetPassword(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
