/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// ApGet - ap/get
func ApGet(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ApShow - ap/show
func ApShow(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FederationDns - federation/dns
func FederationDns(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FederationFollowers - federation/followers
func FederationFollowers(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FederationFollowing - federation/following
func FederationFollowing(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FederationInstances - federation/instances
func FederationInstances(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FederationShowInstance - federation/show-instance
func FederationShowInstance(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FederationUpdateRemoteUser - federation/update-remote-user
func FederationUpdateRemoteUser(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FederationUsers - federation/users
func FederationUsers(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
