/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// AdminAbuseUserReports - admin/abuse-user-reports
func AdminAbuseUserReports(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminAccountsCreate - admin/accounts/create
func AdminAccountsCreate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminAccountsDelete - admin/accounts/delete
func AdminAccountsDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminAdCreate - admin/ad/create
func AdminAdCreate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminAdDelete - admin/ad/delete
func AdminAdDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminAdList - admin/ad/list
func AdminAdList(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminAdUpdate - admin/ad/update
func AdminAdUpdate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminAnnouncementsCreate - admin/announcements/create
func AdminAnnouncementsCreate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminAnnouncementsDelete - admin/announcements/delete
func AdminAnnouncementsDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminAnnouncementsList - admin/announcements/list
func AdminAnnouncementsList(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminAnnouncementsUpdate - admin/announcements/update
func AdminAnnouncementsUpdate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminDeleteAllFilesOfAUser - admin/delete-all-files-of-a-user
func AdminDeleteAllFilesOfAUser(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminDeleteLogs - admin/delete-logs
func AdminDeleteLogs(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminDriveCleanRemoteFiles - admin/drive/clean-remote-files
func AdminDriveCleanRemoteFiles(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminDriveCleanup - admin/drive/cleanup
func AdminDriveCleanup(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminDriveFiles - admin/drive/files
func AdminDriveFiles(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminDriveShowFile - admin/drive/show-file
func AdminDriveShowFile(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminEmojiAdd - admin/emoji/add
func AdminEmojiAdd(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminEmojiCopy - admin/emoji/copy
func AdminEmojiCopy(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminEmojiList - admin/emoji/list
func AdminEmojiList(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminEmojiListRemote - admin/emoji/list-remote
func AdminEmojiListRemote(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminEmojiRemove - admin/emoji/remove
func AdminEmojiRemove(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminEmojiUpdate - admin/emoji/update
func AdminEmojiUpdate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminFederationDeleteAllFiles - admin/federation/delete-all-files
func AdminFederationDeleteAllFiles(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminFederationRefreshRemoteInstanceMetadata - admin/federation/refresh-remote-instance-metadata
func AdminFederationRefreshRemoteInstanceMetadata(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminFederationRemoveAllFollowing - admin/federation/remove-all-following
func AdminFederationRemoveAllFollowing(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminFederationUpdateInstance - admin/federation/update-instance
func AdminFederationUpdateInstance(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminGetIndexStats - admin/get-index-stats
func AdminGetIndexStats(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminGetTableStats - admin/get-table-stats
func AdminGetTableStats(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminInvite - admin/invite
func AdminInvite(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminModeratorsAdd - admin/moderators/add
func AdminModeratorsAdd(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminModeratorsRemove - admin/moderators/remove
func AdminModeratorsRemove(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminPromoCreate - admin/promo/create
func AdminPromoCreate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminQueueClear - admin/queue/clear
func AdminQueueClear(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminQueueDeliverDelayed - admin/queue/deliver-delayed
func AdminQueueDeliverDelayed(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminQueueInboxDelayed - admin/queue/inbox-delayed
func AdminQueueInboxDelayed(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminQueueJobs - admin/queue/jobs
func AdminQueueJobs(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminQueueStats - admin/queue/stats
func AdminQueueStats(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminRelaysAdd - admin/relays/add
func AdminRelaysAdd(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminRelaysList - admin/relays/list
func AdminRelaysList(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminRelaysRemove - admin/relays/remove
func AdminRelaysRemove(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminResetPassword - admin/reset-password
func AdminResetPassword(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminResolveAbuseUserReport - admin/resolve-abuse-user-report
func AdminResolveAbuseUserReport(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminResyncChart - admin/resync-chart
func AdminResyncChart(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminSendEmail - admin/send-email
func AdminSendEmail(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminServerInfo - admin/server-info
func AdminServerInfo(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminShowModerationLogs - admin/show-moderation-logs
func AdminShowModerationLogs(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminShowUser - admin/show-user
func AdminShowUser(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminShowUsers - admin/show-users
func AdminShowUsers(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminSilenceUser - admin/silence-user
func AdminSilenceUser(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminSuspendUser - admin/suspend-user
func AdminSuspendUser(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminUnsilenceUser - admin/unsilence-user
func AdminUnsilenceUser(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminUnsuspendUser - admin/unsuspend-user
func AdminUnsuspendUser(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminUpdateMeta - admin/update-meta
func AdminUpdateMeta(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AdminVacuum - admin/vacuum
func AdminVacuum(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
