/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// AuthSessionGenerate - auth/session/generate
func AuthSessionGenerate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AuthSessionShow - auth/session/show
func AuthSessionShow(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AuthSessionUserkey - auth/session/userkey
func AuthSessionUserkey(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
