/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// ChannelsTimeline - channels/timeline
func ChannelsTimeline(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// Notes - notes
func Notes(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotesChildren - notes/children
func NotesChildren(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotesConversation - notes/conversation
func NotesConversation(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotesCreate - notes/create
func NotesCreate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotesDelete - notes/delete
func NotesDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotesFavoritesCreate - notes/favorites/create
func NotesFavoritesCreate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotesFavoritesDelete - notes/favorites/delete
func NotesFavoritesDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotesFeatured - notes/featured
func NotesFeatured(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotesGlobalTimeline - notes/global-timeline
func NotesGlobalTimeline(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotesHybridTimeline - notes/hybrid-timeline
func NotesHybridTimeline(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotesLocalTimeline - notes/local-timeline
func NotesLocalTimeline(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotesMentions - notes/mentions
func NotesMentions(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotesPollsRecommendation - notes/polls/recommendation
func NotesPollsRecommendation(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotesPollsVote - notes/polls/vote
func NotesPollsVote(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotesReactions - notes/reactions
func NotesReactions(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotesRenotes - notes/renotes
func NotesRenotes(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotesReplies - notes/replies
func NotesReplies(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotesSearch - notes/search
func NotesSearch(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotesSearchByTag - notes/search-by-tag
func NotesSearchByTag(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotesShow - notes/show
func NotesShow(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotesState - notes/state
func NotesState(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotesThreadMutingCreate - notes/thread-muting/create
func NotesThreadMutingCreate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotesThreadMutingDelete - notes/thread-muting/delete
func NotesThreadMutingDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotesTimeline - notes/timeline
func NotesTimeline(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotesTranslate - notes/translate
func NotesTranslate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotesUnrenote - notes/unrenote
func NotesUnrenote(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotesUserListTimeline - notes/user-list-timeline
func NotesUserListTimeline(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotesWatchingCreate - notes/watching/create
func NotesWatchingCreate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotesWatchingDelete - notes/watching/delete
func NotesWatchingDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PromoRead - promo/read
func PromoRead(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
