/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// MessagingHistory - messaging/history
func MessagingHistory(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// MessagingMessages - messaging/messages
func MessagingMessages(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// MessagingMessagesCreate - messaging/messages/create
func MessagingMessagesCreate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// MessagingMessagesDelete - messaging/messages/delete
func MessagingMessagesDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// MessagingMessagesRead - messaging/messages/read
func MessagingMessagesRead(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
