/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// HashtagsList - hashtags/list
func HashtagsList(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// HashtagsSearch - hashtags/search
func HashtagsSearch(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// HashtagsShow - hashtags/show
func HashtagsShow(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// HashtagsTrend - hashtags/trend
func HashtagsTrend(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// HashtagsUsers - hashtags/users
func HashtagsUsers(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
