/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// ClipsCreate - clips/create
func ClipsCreate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ClipsDelete - clips/delete
func ClipsDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ClipsList - clips/list
func ClipsList(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ClipsShow - clips/show
func ClipsShow(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ClipsUpdate - clips/update
func ClipsUpdate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotesClips - notes/clips
func NotesClips(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
