/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// PagesCreate - pages/create
func PagesCreate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PagesDelete - pages/delete
func PagesDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PagesFeatured - pages/featured
func PagesFeatured(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PagesLike - pages/like
func PagesLike(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PagesShow - pages/show
func PagesShow(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PagesUnlike - pages/unlike
func PagesUnlike(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PagesUpdate - pages/update
func PagesUpdate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
