/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// UsersListsCreate - users/lists/create
func UsersListsCreate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersListsDelete - users/lists/delete
func UsersListsDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersListsList - users/lists/list
func UsersListsList(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersListsPull - users/lists/pull
func UsersListsPull(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersListsPush - users/lists/push
func UsersListsPush(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersListsShow - users/lists/show
func UsersListsShow(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersListsUpdate - users/lists/update
func UsersListsUpdate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
