/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// ChartsActiveUsers - charts/active-users
func ChartsActiveUsers(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ChartsDrive - charts/drive
func ChartsDrive(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ChartsFederation - charts/federation
func ChartsFederation(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ChartsHashtag - charts/hashtag
func ChartsHashtag(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ChartsInstance - charts/instance
func ChartsInstance(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ChartsNetwork - charts/network
func ChartsNetwork(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ChartsNotes - charts/notes
func ChartsNotes(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ChartsUserDrive - charts/user/drive
func ChartsUserDrive(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ChartsUserFollowing - charts/user/following
func ChartsUserFollowing(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ChartsUserNotes - charts/user/notes
func ChartsUserNotes(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ChartsUserReactions - charts/user/reactions
func ChartsUserReactions(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ChartsUsers - charts/users
func ChartsUsers(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
