/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// UsersGroupsCreate - users/groups/create
func UsersGroupsCreate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersGroupsDelete - users/groups/delete
func UsersGroupsDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersGroupsInvitationsAccept - users/groups/invitations/accept
func UsersGroupsInvitationsAccept(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersGroupsInvitationsReject - users/groups/invitations/reject
func UsersGroupsInvitationsReject(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersGroupsInvite - users/groups/invite
func UsersGroupsInvite(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersGroupsJoined - users/groups/joined
func UsersGroupsJoined(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersGroupsLeave - users/groups/leave
func UsersGroupsLeave(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersGroupsOwned - users/groups/owned
func UsersGroupsOwned(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersGroupsPull - users/groups/pull
func UsersGroupsPull(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersGroupsShow - users/groups/show
func UsersGroupsShow(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersGroupsTransfer - users/groups/transfer
func UsersGroupsTransfer(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersGroupsUpdate - users/groups/update
func UsersGroupsUpdate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
