/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// NotificationsCreate - notifications/create
func NotificationsCreate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotificationsMarkAllAsRead - notifications/mark-all-as-read
func NotificationsMarkAllAsRead(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotificationsRead - notifications/read
func NotificationsRead(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
