/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GalleryFeatured - gallery/featured
func GalleryFeatured(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GalleryPopular - gallery/popular
func GalleryPopular(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GalleryPosts - gallery/posts
func GalleryPosts(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GalleryPostsCreate - gallery/posts/create
func GalleryPostsCreate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GalleryPostsDelete - gallery/posts/delete
func GalleryPostsDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GalleryPostsLike - gallery/posts/like
func GalleryPostsLike(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GalleryPostsShow - gallery/posts/show
func GalleryPostsShow(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GalleryPostsUnlike - gallery/posts/unlike
func GalleryPostsUnlike(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GalleryPostsUpdate - gallery/posts/update
func GalleryPostsUpdate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
