/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// BlockingCreate - blocking/create
func BlockingCreate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// BlockingDelete - blocking/delete
func BlockingDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// BlockingList - blocking/list
func BlockingList(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ClipsAddNote - clips/add-note
func ClipsAddNote(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ClipsNotes - clips/notes
func ClipsNotes(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// I - i
func I(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// IFavorites - i/favorites
func IFavorites(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// IGalleryLikes - i/gallery/likes
func IGalleryLikes(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// IGalleryPosts - i/gallery/posts
func IGalleryPosts(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// IGetWordMutedNotesCount - i/get-word-muted-notes-count
func IGetWordMutedNotesCount(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// INotifications - i/notifications
func INotifications(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// IPageLikes - i/page-likes
func IPageLikes(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// IPages - i/pages
func IPages(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// IPin - i/pin
func IPin(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// IReadAllMessagingMessages - i/read-all-messaging-messages
func IReadAllMessagingMessages(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// IReadAllUnreadNotes - i/read-all-unread-notes
func IReadAllUnreadNotes(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// IReadAnnouncement - i/read-announcement
func IReadAnnouncement(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// IUnpin - i/unpin
func IUnpin(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// IUpdate - i/update
func IUpdate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// IUserGroupInvites - i/user-group-invites
func IUserGroupInvites(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// MuteCreate - mute/create
func MuteCreate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// MuteDelete - mute/delete
func MuteDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// MuteList - mute/list
func MuteList(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// MyApps - my/apps
func MyApps(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// SwRegister - sw/register
func SwRegister(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// SwUnregister - sw/unregister
func SwUnregister(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
