/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Announcements - announcements
func Announcements(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// Endpoint - endpoint
func Endpoint(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// Endpoints - endpoints
func Endpoints(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GetOnlineUsersCount - get-online-users-count
func GetOnlineUsersCount(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// Meta - meta
func Meta(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// Ping - ping
func Ping(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ServerInfo - server-info
func ServerInfo(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// Stats - stats
func Stats(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
