/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// RoomShow - room/show
func RoomShow(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// RoomUpdate - room/update
func RoomUpdate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
