/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// EmailAddressAvailable - email-address/available
func EmailAddressAvailable(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// PinnedUsers - pinned-users
func PinnedUsers(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsernameAvailable - username/available
func UsernameAvailable(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// Users - users
func Users(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersClips - users/clips
func UsersClips(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersFollowers - users/followers
func UsersFollowers(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersFollowing - users/following
func UsersFollowing(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersGalleryPosts - users/gallery/posts
func UsersGalleryPosts(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersGetFrequentlyRepliedUsers - users/get-frequently-replied-users
func UsersGetFrequentlyRepliedUsers(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersNotes - users/notes
func UsersNotes(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersPages - users/pages
func UsersPages(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersReactions - users/reactions
func UsersReactions(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersRecommendation - users/recommendation
func UsersRecommendation(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersRelation - users/relation
func UsersRelation(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersReportAbuse - users/report-abuse
func UsersReportAbuse(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersSearch - users/search
func UsersSearch(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersSearchByUsernameAndHost - users/search-by-username-and-host
func UsersSearchByUsernameAndHost(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersShow - users/show
func UsersShow(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// UsersStats - users/stats
func UsersStats(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
