/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// AntennasCreate - antennas/create
func AntennasCreate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AntennasDelete - antennas/delete
func AntennasDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AntennasList - antennas/list
func AntennasList(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AntennasNotes - antennas/notes
func AntennasNotes(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AntennasShow - antennas/show
func AntennasShow(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AntennasUpdate - antennas/update
func AntennasUpdate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
