/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// GamesReversiGames - games/reversi/games
func GamesReversiGames(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GamesReversiGamesShow - games/reversi/games/show
func GamesReversiGamesShow(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GamesReversiGamesSurrender - games/reversi/games/surrender
func GamesReversiGamesSurrender(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GamesReversiInvitations - games/reversi/invitations
func GamesReversiInvitations(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GamesReversiMatch - games/reversi/match
func GamesReversiMatch(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// GamesReversiMatchCancel - games/reversi/match/cancel
func GamesReversiMatchCancel(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
