/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// ChannelsCreate - channels/create
func ChannelsCreate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ChannelsFeatured - channels/featured
func ChannelsFeatured(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ChannelsFollow - channels/follow
func ChannelsFollow(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ChannelsFollowed - channels/followed
func ChannelsFollowed(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ChannelsOwned - channels/owned
func ChannelsOwned(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ChannelsShow - channels/show
func ChannelsShow(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ChannelsUnfollow - channels/unfollow
func ChannelsUnfollow(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// ChannelsUpdate - channels/update
func ChannelsUpdate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
