/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// FollowingCreate - following/create
func FollowingCreate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FollowingDelete - following/delete
func FollowingDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FollowingInvalidate - following/invalidate
func FollowingInvalidate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FollowingRequestsAccept - following/requests/accept
func FollowingRequestsAccept(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FollowingRequestsCancel - following/requests/cancel
func FollowingRequestsCancel(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FollowingRequestsList - following/requests/list
func FollowingRequestsList(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// FollowingRequestsReject - following/requests/reject
func FollowingRequestsReject(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
