/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// NotesReactionsCreate - notes/reactions/create
func NotesReactionsCreate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// NotesReactionsDelete - notes/reactions/delete
func NotesReactionsDelete(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
