/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// AppCreate - app/create
func AppCreate(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}

// AppShow - app/show
func AppShow(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}
