/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20030 struct {
	Id string `json:"id"`

	Follower User `json:"follower"`

	Followee User `json:"followee"`
}
