/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject186 struct {
	Title string `json:"title"`

	Name string `json:"name"`

	Summary *string `json:"summary,omitempty"`

	Content []map[string]interface{} `json:"content"`

	Variables []map[string]interface{} `json:"variables"`

	Script string `json:"script"`

	EyeCatchingImageId *string `json:"eyeCatchingImageId,omitempty"`

	Font string `json:"font,omitempty"`

	AlignCenter bool `json:"alignCenter,omitempty"`

	HideTitleWhenPinned bool `json:"hideTitleWhenPinned,omitempty"`
}
