/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2009 struct {
	Id string `json:"id"`

	Inbox string `json:"inbox"`

	Status string `json:"status"`
}
