/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type InlineResponse200 struct {
	Id string `json:"id"`

	CreatedAt time.Time `json:"createdAt"`

	Comment string `json:"comment"`

	Resolved bool `json:"resolved"`

	ReporterId string `json:"reporterId"`

	TargetUserId string `json:"targetUserId"`

	AssigneeId *string `json:"assigneeId"`

	Reporter User `json:"reporter"`

	TargetUser User `json:"targetUser"`

	Assignee User `json:"assignee,omitempty"`
}
