/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject106 struct {
	Host *string `json:"host,omitempty"`

	Blocked *bool `json:"blocked,omitempty"`

	NotResponding *bool `json:"notResponding,omitempty"`

	Suspended *bool `json:"suspended,omitempty"`

	Federating *bool `json:"federating,omitempty"`

	Subscribing *bool `json:"subscribing,omitempty"`

	Publishing *bool `json:"publishing,omitempty"`

	Limit float32 `json:"limit,omitempty"`

	Offset float32 `json:"offset,omitempty"`

	Sort string `json:"sort,omitempty"`
}
