/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type NoteChannel struct {
	Id string `json:"id,omitempty"`

	Name *string `json:"name,omitempty"`
}
