/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject229 struct {
	Query string `json:"query"`

	Offset float32 `json:"offset,omitempty"`

	Limit float32 `json:"limit,omitempty"`

	Origin string `json:"origin,omitempty"`

	Detail bool `json:"detail,omitempty"`
}
