/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RoomUpdateRoomFurnitures struct {
	Id string `json:"id"`

	Type string `json:"type"`

	Position InlineResponse20044Position `json:"position"`

	Rotation InlineResponse20044Position `json:"rotation"`

	Props *map[string]interface{} `json:"props,omitempty"`
}
