/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type Blocking struct {
	Id string `json:"id"`

	CreatedAt time.Time `json:"createdAt"`

	BlockeeId string `json:"blockeeId"`

	Blockee User `json:"blockee"`
}
