/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type Notification struct {
	Id string `json:"id"`

	CreatedAt time.Time `json:"createdAt"`

	IsRead bool `json:"isRead"`

	Type string `json:"type"`

	User User `json:"user,omitempty"`

	UserId *string `json:"userId,omitempty"`

	Note Note `json:"note,omitempty"`

	Reaction *string `json:"reaction,omitempty"`

	Choice *float32 `json:"choice,omitempty"`

	Invitation *map[string]interface{} `json:"invitation,omitempty"`

	Body *string `json:"body,omitempty"`

	Header *string `json:"header,omitempty"`

	Icon *string `json:"icon,omitempty"`
}
