/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type ReversiGameLogs struct {
	At time.Time `json:"at"`

	Color bool `json:"color"`

	Pos float32 `json:"pos"`
}
