/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject143 struct {
	UserId string `json:"userId,omitempty"`

	GroupId string `json:"groupId,omitempty"`

	Limit float32 `json:"limit,omitempty"`

	SinceId string `json:"sinceId,omitempty"`

	UntilId string `json:"untilId,omitempty"`

	MarkAsRead bool `json:"markAsRead,omitempty"`
}
