/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject122 struct {
	PostId string `json:"postId"`

	Title string `json:"title"`

	Description *string `json:"description,omitempty"`

	FileIds []string `json:"fileIds"`

	IsSensitive bool `json:"isSensitive,omitempty"`
}
