/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20022Drive struct {
	TotalFiles []float32 `json:"totalFiles"`

	TotalUsage []float32 `json:"totalUsage"`

	IncFiles []float32 `json:"incFiles"`

	IncUsage []float32 `json:"incUsage"`

	DecFiles []float32 `json:"decFiles"`

	DecUsage []float32 `json:"decUsage"`
}
