/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type User struct {
	Id string `json:"id"`

	Name *string `json:"name"`

	Username string `json:"username"`

	Host *string `json:"host"`

	AvatarUrl *string `json:"avatarUrl"`

	AvatarBlurhash *Any `json:"avatarBlurhash"`

	AvatarColor *Any `json:"avatarColor"`

	IsAdmin bool `json:"isAdmin,omitempty"`

	IsModerator bool `json:"isModerator,omitempty"`

	IsBot bool `json:"isBot,omitempty"`

	IsCat bool `json:"isCat,omitempty"`

	Emojis []UserEmojis `json:"emojis"`

	Url *string `json:"url,omitempty"`

	CreatedAt time.Time `json:"createdAt,omitempty"`

	UpdatedAt *time.Time `json:"updatedAt,omitempty"`

	BannerUrl *string `json:"bannerUrl,omitempty"`

	BannerBlurhash *Any `json:"bannerBlurhash,omitempty"`

	BannerColor *Any `json:"bannerColor,omitempty"`

	IsLocked bool `json:"isLocked,omitempty"`

	IsSuspended bool `json:"isSuspended,omitempty"`

	Description *string `json:"description,omitempty"`

	Location *string `json:"location,omitempty"`

	Birthday *string `json:"birthday,omitempty"`

	Fields []UserFields `json:"fields,omitempty"`

	FollowersCount float32 `json:"followersCount,omitempty"`

	FollowingCount float32 `json:"followingCount,omitempty"`

	NotesCount float32 `json:"notesCount,omitempty"`

	PinnedNoteIds []string `json:"pinnedNoteIds,omitempty"`

	PinnedNotes []Note `json:"pinnedNotes,omitempty"`

	PinnedPageId *string `json:"pinnedPageId,omitempty"`

	PinnedPage Page `json:"pinnedPage,omitempty"`

	TwoFactorEnabled bool `json:"twoFactorEnabled,omitempty"`

	UsePasswordLessLogin bool `json:"usePasswordLessLogin,omitempty"`

	SecurityKeys bool `json:"securityKeys,omitempty"`

	AvatarId *string `json:"avatarId,omitempty"`

	BannerId *string `json:"bannerId,omitempty"`

	AutoWatch bool `json:"autoWatch,omitempty"`

	InjectFeaturedNote bool `json:"injectFeaturedNote,omitempty"`

	AlwaysMarkNsfw bool `json:"alwaysMarkNsfw,omitempty"`

	CarefulBot bool `json:"carefulBot,omitempty"`

	AutoAcceptFollowed bool `json:"autoAcceptFollowed,omitempty"`

	HasUnreadSpecifiedNotes bool `json:"hasUnreadSpecifiedNotes,omitempty"`

	HasUnreadMentions bool `json:"hasUnreadMentions,omitempty"`

	HasUnreadAnnouncement bool `json:"hasUnreadAnnouncement,omitempty"`

	HasUnreadAntenna bool `json:"hasUnreadAntenna,omitempty"`

	HasUnreadChannel bool `json:"hasUnreadChannel,omitempty"`

	HasUnreadMessagingMessage bool `json:"hasUnreadMessagingMessage,omitempty"`

	HasUnreadNotification bool `json:"hasUnreadNotification,omitempty"`

	HasPendingReceivedFollowRequest bool `json:"hasPendingReceivedFollowRequest,omitempty"`

	Integrations map[string]interface{} `json:"integrations,omitempty"`

	MutedWords Array `json:"mutedWords,omitempty"`

	MutedInstances Array `json:"mutedInstances,omitempty"`

	MutingNotificationTypes Array `json:"mutingNotificationTypes,omitempty"`

	IsFollowing bool `json:"isFollowing,omitempty"`

	HasPendingFollowRequestFromYou bool `json:"hasPendingFollowRequestFromYou,omitempty"`

	HasPendingFollowRequestToYou bool `json:"hasPendingFollowRequestToYou,omitempty"`

	IsFollowed bool `json:"isFollowed,omitempty"`

	IsBlocking bool `json:"isBlocking,omitempty"`

	IsBlocked bool `json:"isBlocked,omitempty"`

	IsMuted bool `json:"isMuted,omitempty"`
}
