/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject69 struct {
	Span string `json:"span"`

	Limit float32 `json:"limit,omitempty"`

	Offset *float32 `json:"offset,omitempty"`

	Tag string `json:"tag"`
}
