/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20023 struct {
	IncomingRequests []float32 `json:"incomingRequests"`

	OutgoingRequests []float32 `json:"outgoingRequests"`

	TotalTime []float32 `json:"totalTime"`

	IncomingBytes []float32 `json:"incomingBytes"`

	OutgoingBytes []float32 `json:"outgoingBytes"`
}
