/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type InlineResponse20013 struct {
	Id string `json:"id"`

	CreatedAt time.Time `json:"createdAt"`

	UpdatedAt *time.Time `json:"updatedAt"`

	LastFetchedAt *string `json:"lastFetchedAt"`

	Username string `json:"username"`

	Name string `json:"name"`

	FolowersCount float32 `json:"folowersCount"`

	FollowingCount float32 `json:"followingCount"`

	NotesCount float32 `json:"notesCount"`

	AvatarId *string `json:"avatarId"`

	BannerId *string `json:"bannerId"`

	Tags []string `json:"tags"`

	AvatarUrl *string `json:"avatarUrl"`

	BannerUrl *string `json:"bannerUrl"`

	AvatarBlurhash *Any `json:"avatarBlurhash"`

	BannerBlurhash *Any `json:"bannerBlurhash"`

	IsSuspended bool `json:"isSuspended"`

	IsSilenced bool `json:"isSilenced"`

	IsLocked bool `json:"isLocked"`

	IsBot bool `json:"isBot"`

	IsCat bool `json:"isCat"`

	IsAdmin bool `json:"isAdmin"`

	IsModerator bool `json:"isModerator"`

	Emojis []string `json:"emojis"`

	Host *string `json:"host"`

	Inbox *string `json:"inbox"`

	SharedInbox *string `json:"sharedInbox"`

	Featured *string `json:"featured"`

	Uri *string `json:"uri"`

	Token string `json:"token"`
}
