/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type NotesCreatePoll struct {
	Choices []string `json:"choices"`

	Multiple bool `json:"multiple,omitempty"`

	ExpiresAt *float32 `json:"expiresAt,omitempty"`

	ExpiredAfter *float32 `json:"expiredAfter,omitempty"`
}
