/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type QueueCount struct {
	Waiting float32 `json:"waiting"`

	Active float32 `json:"active"`

	Completed float32 `json:"completed"`

	Failed float32 `json:"failed"`

	Delayed float32 `json:"delayed"`

	Paused float32 `json:"paused"`
}
