/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type Muting struct {
	Id string `json:"id"`

	CreatedAt time.Time `json:"createdAt"`

	MuteeId string `json:"muteeId"`

	Mutee User `json:"mutee"`
}
