/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject130 struct {
	Tag string `json:"tag"`

	Limit float32 `json:"limit,omitempty"`

	Sort string `json:"sort"`

	State string `json:"state,omitempty"`

	Origin string `json:"origin,omitempty"`
}
