/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20025Local struct {
	Followings InlineResponse20021Instance `json:"followings"`

	Followers InlineResponse20021Instance `json:"followers"`
}
