/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type DriveFolder struct {
	Id string `json:"id"`

	CreatedAt time.Time `json:"createdAt"`

	Name string `json:"name"`

	FoldersCount float32 `json:"foldersCount,omitempty"`

	FilesCount float32 `json:"filesCount,omitempty"`

	ParentId *string `json:"parentId"`

	Parent DriveFolder `json:"parent,omitempty"`
}
