/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// ErrorError - An error object.
type ErrorError struct {

	// An error code. Unique within the endpoint.
	Code string `json:"code"`

	// An error message.
	Message string `json:"message"`

	// An error ID. This ID is static.
	Id string `json:"id"`
}
