/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject203 struct {
	UserId string `json:"userId,omitempty"`

	Username string `json:"username,omitempty"`

	Host *string `json:"host,omitempty"`

	SinceId string `json:"sinceId,omitempty"`

	UntilId string `json:"untilId,omitempty"`

	Limit float32 `json:"limit,omitempty"`
}
