/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type Hashtag struct {
	Tag string `json:"tag"`

	MentionedUsersCount float32 `json:"mentionedUsersCount"`

	MentionedLocalUsersCount float32 `json:"mentionedLocalUsersCount"`

	MentionedRemoteUsersCount float32 `json:"mentionedRemoteUsersCount"`

	AttachedUsersCount float32 `json:"attachedUsersCount"`

	AttachedLocalUsersCount float32 `json:"attachedLocalUsersCount"`

	AttachedRemoteUsersCount float32 `json:"attachedRemoteUsersCount"`
}
