/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20039 struct {
	MaintainerName *string `json:"maintainerName"`

	MaintainerEmail *string `json:"maintainerEmail"`

	Version string `json:"version"`

	Name string `json:"name"`

	Uri string `json:"uri"`

	Description *string `json:"description"`

	Langs []string `json:"langs"`

	TosUrl *string `json:"tosUrl"`

	RepositoryUrl string `json:"repositoryUrl"`

	FeedbackUrl string `json:"feedbackUrl"`

	Secure bool `json:"secure"`

	DisableRegistration bool `json:"disableRegistration"`

	DisableLocalTimeline bool `json:"disableLocalTimeline"`

	DisableGlobalTimeline bool `json:"disableGlobalTimeline"`

	DriveCapacityPerLocalUserMb float32 `json:"driveCapacityPerLocalUserMb"`

	DriveCapacityPerRemoteUserMb float32 `json:"driveCapacityPerRemoteUserMb"`

	CacheRemoteFiles bool `json:"cacheRemoteFiles"`

	ProxyRemoteFiles bool `json:"proxyRemoteFiles"`

	EmailRequiredForSignup bool `json:"emailRequiredForSignup"`

	EnableHcaptcha bool `json:"enableHcaptcha"`

	HcaptchaSiteKey *string `json:"hcaptchaSiteKey"`

	EnableRecaptcha bool `json:"enableRecaptcha"`

	RecaptchaSiteKey *string `json:"recaptchaSiteKey"`

	SwPublickey *string `json:"swPublickey"`

	MascotImageUrl string `json:"mascotImageUrl"`

	BannerUrl string `json:"bannerUrl"`

	ErrorImageUrl string `json:"errorImageUrl"`

	IconUrl *string `json:"iconUrl"`

	MaxNoteTextLength float32 `json:"maxNoteTextLength"`

	Emojis []InlineResponse20039Emojis `json:"emojis"`

	Ads []InlineResponse20039Ads `json:"ads"`

	RequireSetup bool `json:"requireSetup"`

	EnableEmail bool `json:"enableEmail"`

	EnableTwitterIntegration bool `json:"enableTwitterIntegration"`

	EnableGithubIntegration bool `json:"enableGithubIntegration"`

	EnableDiscordIntegration bool `json:"enableDiscordIntegration"`

	EnableServiceWorker bool `json:"enableServiceWorker"`

	TranslatorAvailable bool `json:"translatorAvailable"`

	ProxyAccountName *string `json:"proxyAccountName"`

	Features InlineResponse20039Features `json:"features,omitempty"`

	UserStarForReactionFallback bool `json:"userStarForReactionFallback,omitempty"`

	PinnedUsers []string `json:"pinnedUsers,omitempty"`

	HiddenTags []string `json:"hiddenTags,omitempty"`

	BlockedHosts []string `json:"blockedHosts,omitempty"`

	HcaptchaSecretKey *string `json:"hcaptchaSecretKey,omitempty"`

	RecaptchaSecretKey *string `json:"recaptchaSecretKey,omitempty"`

	ProxyAccountId *string `json:"proxyAccountId,omitempty"`

	TwitterConsumerKey *string `json:"twitterConsumerKey,omitempty"`

	TwitterConsumerSecret *string `json:"twitterConsumerSecret,omitempty"`

	GithubClientId *string `json:"githubClientId,omitempty"`

	GithubClientSecret *string `json:"githubClientSecret,omitempty"`

	DiscordClientId *string `json:"discordClientId,omitempty"`

	DiscordClientSecret *string `json:"discordClientSecret,omitempty"`

	SummaryProxy *string `json:"summaryProxy,omitempty"`

	Email *string `json:"email,omitempty"`

	SmtpSecure bool `json:"smtpSecure,omitempty"`

	SmtpHost *string `json:"smtpHost,omitempty"`

	SmtpPort *string `json:"smtpPort,omitempty"`

	SmtpUser *string `json:"smtpUser,omitempty"`

	SmtpPass *string `json:"smtpPass,omitempty"`

	SwPrivateKey *string `json:"swPrivateKey,omitempty"`

	UseObjectStorage bool `json:"useObjectStorage,omitempty"`

	ObjectStorageBaseUrl *string `json:"objectStorageBaseUrl,omitempty"`

	ObjectStorageBucket *string `json:"objectStorageBucket,omitempty"`

	ObjectStoragePrefix *string `json:"objectStoragePrefix,omitempty"`

	ObjectStorageEndpoint *string `json:"objectStorageEndpoint,omitempty"`

	ObjectStorageRegion *string `json:"objectStorageRegion,omitempty"`

	ObjectStoragePort *float32 `json:"objectStoragePort,omitempty"`

	ObjectStorageAccessKey *string `json:"objectStorageAccessKey,omitempty"`

	ObjectStorageSecretKey *string `json:"objectStorageSecretKey,omitempty"`

	ObjectStorageUseSSL bool `json:"objectStorageUseSSL,omitempty"`

	ObjectStorageUseProxy bool `json:"objectStorageUseProxy,omitempty"`

	ObjectStorageSetPublicRead bool `json:"objectStorageSetPublicRead,omitempty"`
}
