/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject197 struct {
	Endpoint string `json:"endpoint"`

	Auth string `json:"auth"`

	Publickey string `json:"publickey"`
}
