/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject79 struct {
	Name string `json:"name"`

	IsPublic bool `json:"isPublic,omitempty"`

	Description *string `json:"description,omitempty"`
}
