/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type Note struct {
	Id string `json:"id"`

	CreatedAt time.Time `json:"createdAt"`

	Text *string `json:"text"`

	Cw *string `json:"cw,omitempty"`

	UserId string `json:"userId"`

	User User `json:"user"`

	ReplyId *string `json:"replyId,omitempty"`

	RenoteId *string `json:"renoteId,omitempty"`

	Reply Note `json:"reply,omitempty"`

	Renote Note `json:"renote,omitempty"`

	IsHidden bool `json:"isHidden,omitempty"`

	Visibility string `json:"visibility"`

	Mentions []string `json:"mentions,omitempty"`

	VisibleUserIds []string `json:"visibleUserIds,omitempty"`

	FileIds []string `json:"fileIds,omitempty"`

	Files []DriveFile `json:"files,omitempty"`

	Tags []string `json:"tags,omitempty"`

	Poll *map[string]interface{} `json:"poll,omitempty"`

	ChannelId *string `json:"channelId,omitempty"`

	Channel *[]NoteChannel `json:"channel,omitempty"`

	LocalOnly bool `json:"localOnly,omitempty"`

	Emojis []NoteEmojis `json:"emojis"`

	Reactions map[string]interface{} `json:"reactions"`

	RenoteCount float32 `json:"renoteCount"`

	RepliesCount float32 `json:"repliesCount"`

	Uri string `json:"uri,omitempty"`

	Url string `json:"url,omitempty"`

	MyReaction *map[string]interface{} `json:"myReaction,omitempty"`
}
