/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject144 struct {
	UserId string `json:"userId,omitempty"`

	GroupId string `json:"groupId,omitempty"`

	Text string `json:"text,omitempty"`

	FileId string `json:"fileId,omitempty"`
}
