/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type FederationInstance struct {
	Id string `json:"id"`

	CaughtAt time.Time `json:"caughtAt"`

	Host string `json:"host"`

	UsersCount float32 `json:"usersCount"`

	NotesCount float32 `json:"notesCount"`

	FollowingCount float32 `json:"followingCount"`

	FollowersCount float32 `json:"followersCount"`

	DriveUsage float32 `json:"driveUsage"`

	DriveFiles float32 `json:"driveFiles"`

	LatestRequestSentAt *time.Time `json:"latestRequestSentAt"`

	LastCommunicatedAt time.Time `json:"lastCommunicatedAt"`

	IsNotResponding bool `json:"isNotResponding"`

	IsSuspended bool `json:"isSuspended"`

	SoftwareName *string `json:"softwareName"`

	SoftwareVersion *string `json:"softwareVersion"`

	OpenRegistrations *bool `json:"openRegistrations"`

	Name *string `json:"name"`

	Description *string `json:"description"`

	MaintainerName *string `json:"maintainerName"`

	MaintainerEmail *string `json:"maintainerEmail"`

	IconUrl *string `json:"iconUrl"`

	InfoUpdatedAt *time.Time `json:"infoUpdatedAt"`
}
