/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20020 struct {
	Local InlineResponse20020Local `json:"local"`

	Remote InlineResponse20020Local `json:"remote"`
}
