/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type Channel struct {
	Id string `json:"id"`

	CreatedAt time.Time `json:"createdAt"`

	LastNotedAt *time.Time `json:"lastNotedAt"`

	Name string `json:"name"`

	Description *string `json:"description"`

	BannerUrl *string `json:"bannerUrl"`

	NotesCount float32 `json:"notesCount"`

	UsersCount float32 `json:"usersCount"`

	IsFollowing bool `json:"isFollowing,omitempty"`

	UserId *string `json:"userId"`
}
