/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject128 struct {
	Limit float32 `json:"limit,omitempty"`

	Query string `json:"query"`

	Offset float32 `json:"offset,omitempty"`
}
