/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20040 struct {
	Id string `json:"id"`

	Name string `json:"name"`

	CallbackUrl string `json:"callbackUrl"`

	Permission []string `json:"permission"`

	Secret string `json:"secret,omitempty"`

	IsAuthorized MyAppsIsAuthorized `json:"isAuthorized,omitempty"`
}
