/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20021Instance struct {
	Total []float32 `json:"total"`

	Inc []float32 `json:"inc"`

	Dec []float32 `json:"dec"`
}
