/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject65 struct {
	ChannelId string `json:"channelId"`

	Name string `json:"name,omitempty"`

	Description *string `json:"description,omitempty"`

	BannerId *string `json:"bannerId,omitempty"`
}
