/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20034 struct {
	Tag string `json:"tag"`

	Chart []float32 `json:"chart"`

	UsersCount float32 `json:"usersCount"`
}
