/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type App struct {
	Id string `json:"id"`

	Name string `json:"name"`

	CallbackUrl *string `json:"callbackUrl"`

	Permission []string `json:"permission"`

	Secret string `json:"secret,omitempty"`

	IsAuthorized bool `json:"isAuthorized,omitempty"`
}
