/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type InlineResponse20033 struct {
	Id string `json:"id"`

	CreatedAt time.Time `json:"createdAt"`

	ParentId string `json:"parentId"`

	Parent User `json:"parent"`

	ChildId string `json:"childId"`

	Child User `json:"child"`
}
