/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20022Requests struct {
	Failed []float32 `json:"failed"`

	Succeeded []float32 `json:"succeeded"`

	Received []float32 `json:"received"`
}
