/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject19 struct {
	Id string `json:"id"`

	Name string `json:"name"`

	Category *string `json:"category,omitempty"`

	Aliases []string `json:"aliases"`
}
