/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type Clip struct {
	Id string `json:"id"`

	CreatedAt time.Time `json:"createdAt"`

	UserId string `json:"userId"`

	User User `json:"user"`

	Name string `json:"name"`

	Description *string `json:"description"`

	IsPublic bool `json:"isPublic"`
}
