/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20044 struct {
	RoomType string `json:"roomType"`

	Furnitures []InlineResponse20044Furnitures `json:"furnitures"`

	CarpetColor string `json:"carpetColor"`
}
