/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type MyAppsIsAuthorized struct {
	AppId string `json:"appId"`

	UserId string `json:"userId"`
}
