/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type DriveFileProperties struct {
	Width float32 `json:"width,omitempty"`

	Height float32 `json:"height,omitempty"`

	Orientation float32 `json:"orientation,omitempty"`

	AvgColor string `json:"avgColor,omitempty"`
}
