/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject10 struct {
	Id string `json:"id"`

	Title string `json:"title"`

	Text string `json:"text"`

	ImageUrl *string `json:"imageUrl"`
}
