/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type InlineResponse20012 struct {
	Id string `json:"id"`

	CreatedAt time.Time `json:"createdAt"`

	Type string `json:"type"`

	Info map[string]interface{} `json:"info"`

	UserId string `json:"userId"`

	User User `json:"user"`
}
