/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type DriveFile struct {
	Id string `json:"id"`

	CreatedAt time.Time `json:"createdAt"`

	Name string `json:"name"`

	Type string `json:"type"`

	Md5 string `json:"md5"`

	Size float32 `json:"size"`

	IsSensitive bool `json:"isSensitive"`

	Blurhash *string `json:"blurhash"`

	Properties DriveFileProperties `json:"properties"`

	Url *string `json:"url"`

	ThumbnailUrl *string `json:"thumbnailUrl"`

	Comment *string `json:"comment"`

	FolderId *string `json:"folderId"`

	Folder DriveFolder `json:"folder,omitempty"`

	UserId *string `json:"userId"`

	User User `json:"user,omitempty"`
}
