/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject40 struct {
	DisableRegistration *bool `json:"disableRegistration,omitempty"`

	DisableLocalTimeline *bool `json:"disableLocalTimeline,omitempty"`

	DisableGlobalTimeline *bool `json:"disableGlobalTimeline,omitempty"`

	UseStarForReactionFallback *bool `json:"useStarForReactionFallback,omitempty"`

	PinnedUsers *[]string `json:"pinnedUsers,omitempty"`

	HiddenTags *[]string `json:"hiddenTags,omitempty"`

	BlockedHosts *[]string `json:"blockedHosts,omitempty"`

	MascotImageUrl *string `json:"mascotImageUrl,omitempty"`

	BannerUrl *string `json:"bannerUrl,omitempty"`

	ErrorImageUrl *string `json:"errorImageUrl,omitempty"`

	IconUrl *string `json:"iconUrl,omitempty"`

	BackgroundImageUrl *string `json:"backgroundImageUrl,omitempty"`

	LogoImageUrl *string `json:"logoImageUrl,omitempty"`

	Name *string `json:"name,omitempty"`

	Description *string `json:"description,omitempty"`

	MaxNoteTextLength float32 `json:"maxNoteTextLength,omitempty"`

	LocalDriveCapacityMb float32 `json:"localDriveCapacityMb,omitempty"`

	RemoteDriveCapacityMb float32 `json:"remoteDriveCapacityMb,omitempty"`

	CacheRemoteFiles bool `json:"cacheRemoteFiles,omitempty"`

	ProxyRemoteFiles bool `json:"proxyRemoteFiles,omitempty"`

	EmailRequiredForSignup bool `json:"emailRequiredForSignup,omitempty"`

	EnableHcaptcha bool `json:"enableHcaptcha,omitempty"`

	HcaptchaSiteKey *string `json:"hcaptchaSiteKey,omitempty"`

	HcaptchaSecretKey *string `json:"hcaptchaSecretKey,omitempty"`

	EnableRecaptcha bool `json:"enableRecaptcha,omitempty"`

	RecaptchaSiteKey *string `json:"recaptchaSiteKey,omitempty"`

	RecaptchaSecretKey *string `json:"recaptchaSecretKey,omitempty"`

	ProxyAccountId *string `json:"proxyAccountId,omitempty"`

	MaintainerName *string `json:"maintainerName,omitempty"`

	MaintainerEmail *string `json:"maintainerEmail,omitempty"`

	PinnedPages []string `json:"pinnedPages,omitempty"`

	PinnedClipId *string `json:"pinnedClipId,omitempty"`

	Langs []string `json:"langs,omitempty"`

	SummalyProxy *string `json:"summalyProxy,omitempty"`

	DeeplAuthKey *string `json:"deeplAuthKey,omitempty"`

	DeeplIsPro bool `json:"deeplIsPro,omitempty"`

	EnableTwitterIntegration bool `json:"enableTwitterIntegration,omitempty"`

	TwitterConsumerKey *string `json:"twitterConsumerKey,omitempty"`

	TwitterConsumerSecret *string `json:"twitterConsumerSecret,omitempty"`

	EnableGithubIntegration bool `json:"enableGithubIntegration,omitempty"`

	GithubClientId *string `json:"githubClientId,omitempty"`

	GithubClientSecret *string `json:"githubClientSecret,omitempty"`

	EnableDiscordIntegration bool `json:"enableDiscordIntegration,omitempty"`

	DiscordClientId *string `json:"discordClientId,omitempty"`

	DiscordClientSecret *string `json:"discordClientSecret,omitempty"`

	EnableEmail bool `json:"enableEmail,omitempty"`

	Email *string `json:"email,omitempty"`

	SmtpSecure bool `json:"smtpSecure,omitempty"`

	SmtpHost *string `json:"smtpHost,omitempty"`

	SmtpPort *float32 `json:"smtpPort,omitempty"`

	SmtpUser *string `json:"smtpUser,omitempty"`

	SmtpPass *string `json:"smtpPass,omitempty"`

	EnableServiceWorker bool `json:"enableServiceWorker,omitempty"`

	SwPublicKey *string `json:"swPublicKey,omitempty"`

	SwPrivateKey *string `json:"swPrivateKey,omitempty"`

	TosUrl *string `json:"tosUrl,omitempty"`

	RepositoryUrl string `json:"repositoryUrl,omitempty"`

	FeedbackUrl string `json:"feedbackUrl,omitempty"`

	UseObjectStorage bool `json:"useObjectStorage,omitempty"`

	ObjectStorageBaseUrl *string `json:"objectStorageBaseUrl,omitempty"`

	ObjectStorageBucket *string `json:"objectStorageBucket,omitempty"`

	ObjectStoragePrefix *string `json:"objectStoragePrefix,omitempty"`

	ObjectStorageEndpoint *string `json:"objectStorageEndpoint,omitempty"`

	ObjectStorageRegion *string `json:"objectStorageRegion,omitempty"`

	ObjectStoragePort *float32 `json:"objectStoragePort,omitempty"`

	ObjectStorageAccessKey *string `json:"objectStorageAccessKey,omitempty"`

	ObjectStorageSecretKey *string `json:"objectStorageSecretKey,omitempty"`

	ObjectStorageUseSSL bool `json:"objectStorageUseSSL,omitempty"`

	ObjectStorageUseProxy bool `json:"objectStorageUseProxy,omitempty"`

	ObjectStorageSetPublicRead bool `json:"objectStorageSetPublicRead,omitempty"`

	ObjectStorageS3ForcePathStyle bool `json:"objectStorageS3ForcePathStyle,omitempty"`
}
