/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject43 struct {
	Name string `json:"name"`

	Src string `json:"src"`

	UserListId *string `json:"userListId,omitempty"`

	UserGroupId *string `json:"userGroupId,omitempty"`

	Keywords [][]string `json:"keywords"`

	ExcludeKeywords [][]string `json:"excludeKeywords"`

	Users []string `json:"users"`

	CaseSensitive bool `json:"caseSensitive"`

	WithReplies bool `json:"withReplies"`

	WithFile bool `json:"withFile"`

	Notify bool `json:"notify"`
}
