/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20044Position struct {
	X float32 `json:"x"`

	Y float32 `json:"y"`

	Z float32 `json:"z"`
}
