/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2007 struct {
	Id string `json:"id"`

	Data map[string]interface{} `json:"data"`

	Attempts float32 `json:"attempts"`

	MaxAttempts float32 `json:"maxAttempts"`

	Timestamp float32 `json:"timestamp"`
}
