/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject6 struct {
	Id string `json:"id"`

	Memo string `json:"memo"`

	Url string `json:"url"`

	ImageUrl string `json:"imageUrl"`

	Place string `json:"place"`

	Priority string `json:"priority"`

	Ratio float32 `json:"ratio"`

	ExpiresAt float32 `json:"expiresAt"`
}
