/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject27 struct {
	Domain string `json:"domain"`

	State string `json:"state"`

	Limit float32 `json:"limit,omitempty"`
}
