/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RoomUpdateRoom struct {
	Furnitures []RoomUpdateRoomFurnitures `json:"furnitures"`

	RoomType string `json:"roomType"`

	CarpetColor string `json:"carpetColor"`
}
