/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject228 struct {
	Username *string `json:"username,omitempty"`

	Host *string `json:"host,omitempty"`

	Limit float32 `json:"limit,omitempty"`

	Detail bool `json:"detail,omitempty"`
}
