/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject87 struct {
	FolderId *string `json:"folderId,omitempty"`

	Name *string `json:"name,omitempty"`

	IsSensitive Either `json:"isSensitive,omitempty"`

	Force Either `json:"force,omitempty"`
}
