/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20045 struct {
	NotesCount float32 `json:"notesCount"`

	OriginalNotesCount float32 `json:"originalNotesCount"`

	UsersCount float32 `json:"usersCount"`

	OriginalUsersCount float32 `json:"originalUsersCount"`

	Instances float32 `json:"instances"`

	DriveUsageLocal float32 `json:"driveUsageLocal"`

	DriveUsageRemote float32 `json:"driveUsageRemote"`
}
