/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2008 struct {
	Deliver QueueCount `json:"deliver"`

	Inbox QueueCount `json:"inbox"`

	Db QueueCount `json:"db"`

	ObjectStorage QueueCount `json:"objectStorage"`
}
