/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type MessagingMessage struct {
	Id string `json:"id"`

	CreatedAt time.Time `json:"createdAt"`

	UserId string `json:"userId"`

	User User `json:"user,omitempty"`

	Text *string `json:"text"`

	FileId *string `json:"fileId,omitempty"`

	File DriveFile `json:"file,omitempty"`

	RecipientId *string `json:"recipientId"`

	Recipient User `json:"recipient,omitempty"`

	GroupId *string `json:"groupId"`

	Group UserGroup `json:"group,omitempty"`

	IsRead bool `json:"isRead,omitempty"`

	Reads []string `json:"reads,omitempty"`
}
