/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20022NotesDiffs struct {
	Normal []float32 `json:"normal"`

	Reply []float32 `json:"reply"`

	Renote []float32 `json:"renote"`
}
