/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject95 struct {
	Name string `json:"name,omitempty"`

	ParentId *string `json:"parentId,omitempty"`
}
