/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20011 struct {
	Machine string `json:"machine"`

	Os string `json:"os"`

	Node string `json:"node"`

	Psql string `json:"psql"`

	Cpu InlineResponse20011Cpu `json:"cpu"`

	Mem InlineResponse20011Mem `json:"mem"`

	Fs InlineResponse20011Fs `json:"fs"`

	Net InlineResponse20011Net `json:"net"`
}
