/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20039Ads struct {
	Place string `json:"place"`

	Url string `json:"url"`

	ImageUrl string `json:"imageUrl"`
}
