/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject127 struct {
	Limit float32 `json:"limit,omitempty"`

	AttachedToUserOnly bool `json:"attachedToUserOnly,omitempty"`

	AttachedToLocalUserOnly bool `json:"attachedToLocalUserOnly,omitempty"`

	AttachedToRemoteUserOnly bool `json:"attachedToRemoteUserOnly,omitempty"`

	Sort string `json:"sort"`
}
