/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type Following struct {
	Id string `json:"id"`

	CreatedAt time.Time `json:"createdAt"`

	FolloweeId string `json:"followeeId"`

	Followee User `json:"followee,omitempty"`

	FollowerId string `json:"followerId"`

	Follower User `json:"follower,omitempty"`
}
