/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20039Features struct {
	Registration bool `json:"registration"`

	LocalTimeLine bool `json:"localTimeLine"`

	GlobalTimeLine bool `json:"globalTimeLine"`

	Elasticsearch bool `json:"elasticsearch"`

	Hcaptcha bool `json:"hcaptcha"`

	Recaptcha bool `json:"recaptcha"`

	ObjectStorage bool `json:"objectStorage"`

	Twitter bool `json:"twitter"`

	Github bool `json:"github"`

	Discord bool `json:"discord"`

	ServiceWorker bool `json:"serviceWorker"`

	Miauth bool `json:"miauth,omitempty"`
}
