/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject92 struct {
	FileId string `json:"fileId"`

	FolderId *string `json:"folderId,omitempty"`

	Name string `json:"name,omitempty"`

	IsSensitive bool `json:"isSensitive,omitempty"`

	Comment *string `json:"comment,omitempty"`
}
