/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type GalleryPost struct {
	Id string `json:"id"`

	CreatedAt time.Time `json:"createdAt"`

	UpdatedAt time.Time `json:"updatedAt"`

	Title string `json:"title"`

	Description *string `json:"description"`

	UserId string `json:"userId"`

	User User `json:"user"`

	FileIds []string `json:"fileIds,omitempty"`

	Files []DriveFile `json:"files,omitempty"`

	Tags []string `json:"tags,omitempty"`

	IsSensitive bool `json:"isSensitive"`
}
