/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject134 struct {
	Limit float32 `json:"limit,omitempty"`

	SinceId string `json:"sinceId,omitempty"`

	UntilId string `json:"untilId,omitempty"`

	Following bool `json:"following,omitempty"`

	UnreadOnly bool `json:"unreadOnly,omitempty"`

	MarkAsRead bool `json:"markAsRead,omitempty"`

	IncludeTypes []string `json:"includeTypes,omitempty"`

	ExcludeTypes []string `json:"excludeTypes,omitempty"`
}
