/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type Antenna struct {
	Id string `json:"id"`

	CreatedAt time.Time `json:"createdAt"`

	Name string `json:"name"`

	Keywords [][]string `json:"keywords"`

	ExcludeKeywords [][]string `json:"excludeKeywords"`

	Src string `json:"src"`

	UserListId *string `json:"userListId"`

	UserGroupId *string `json:"userGroupId"`

	Users []string `json:"users"`

	CaseSensitive bool `json:"caseSensitive"`

	Notify bool `json:"notify"`

	WithReplies bool `json:"withReplies"`

	WithFile bool `json:"withFile"`

	HasUnreadNote bool `json:"hasUnreadNote"`
}
