/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject156 struct {
	Visibility string `json:"visibility,omitempty"`

	VisibleUserIds []string `json:"visibleUserIds,omitempty"`

	Text *string `json:"text,omitempty"`

	Cw *string `json:"cw,omitempty"`

	LocalOnly bool `json:"localOnly,omitempty"`

	NoExtractMentions bool `json:"noExtractMentions,omitempty"`

	NoExtractHashtags bool `json:"noExtractHashtags,omitempty"`

	NoExtractEmojis bool `json:"noExtractEmojis,omitempty"`

	FileIds []string `json:"fileIds,omitempty"`

	// Deprecated
	MediaIds []string `json:"mediaIds,omitempty"`

	ReplyId *string `json:"replyId,omitempty"`

	RenoteId *string `json:"renoteId,omitempty"`

	ChannelId *string `json:"channelId,omitempty"`

	Poll *NotesCreatePoll `json:"poll,omitempty"`
}
