/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20022 struct {
	Requests InlineResponse20022Requests `json:"requests"`

	Notes InlineResponse20022Notes `json:"notes"`

	Users InlineResponse20021Instance `json:"users"`

	Following InlineResponse20021Instance `json:"following"`

	Followers InlineResponse20021Instance `json:"followers"`

	Drive InlineResponse20022Drive `json:"drive"`
}
