/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject50 struct {
	Name string `json:"name"`

	Description string `json:"description"`

	Permission []string `json:"permission"`

	CallbackUrl *string `json:"callbackUrl,omitempty"`
}
