/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type InlineResponse2003 struct {
	Id string `json:"id"`

	CreatedAt time.Time `json:"createdAt"`

	UserId *string `json:"userId"`

	UserHost *string `json:"userHost"`

	Md5 string `json:"md5"`

	Name string `json:"name"`

	Type string `json:"type"`

	Size float32 `json:"size"`

	Comment *string `json:"comment"`

	Blurhash *string `json:"blurhash"`

	Properties InlineResponse2003Properties `json:"properties"`

	StoredInternal *bool `json:"storedInternal"`

	Url *string `json:"url"`

	ThumbnailUrl *string `json:"thumbnailUrl"`

	WebpublicUrl *string `json:"webpublicUrl"`

	AccessKey string `json:"accessKey"`

	ThumbnailAccessKey string `json:"thumbnailAccessKey"`

	WebpublicAccessKey string `json:"webpublicAccessKey"`

	Uri *string `json:"uri"`

	Src *string `json:"src"`

	FolderId *string `json:"folderId"`

	IsSensitive bool `json:"isSensitive"`

	IsLink bool `json:"isLink"`
}
