/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject93 struct {
	Url string `json:"url"`

	FolderId *string `json:"folderId,omitempty"`

	IsSensitive bool `json:"isSensitive,omitempty"`

	Comment *string `json:"comment,omitempty"`

	Marker *string `json:"marker,omitempty"`

	Force bool `json:"force,omitempty"`
}
