/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject140 struct {
	Name *Any `json:"name,omitempty"`

	Description *Any `json:"description,omitempty"`

	Lang *string `json:"lang,omitempty"`

	Location *Any `json:"location,omitempty"`

	Birthday *Any `json:"birthday,omitempty"`

	AvatarId *string `json:"avatarId,omitempty"`

	BannerId *string `json:"bannerId,omitempty"`

	Fields []map[string]interface{} `json:"fields,omitempty"`

	IsLocked bool `json:"isLocked,omitempty"`

	IsExplorable bool `json:"isExplorable,omitempty"`

	HideOnlineStatus bool `json:"hideOnlineStatus,omitempty"`

	PublicReactions bool `json:"publicReactions,omitempty"`

	FfVisibility string `json:"ffVisibility,omitempty"`

	CarefulBot bool `json:"carefulBot,omitempty"`

	AutoAcceptFollowed bool `json:"autoAcceptFollowed,omitempty"`

	NoCrawle bool `json:"noCrawle,omitempty"`

	IsBot bool `json:"isBot,omitempty"`

	IsCat bool `json:"isCat,omitempty"`

	InjectFeaturedNote bool `json:"injectFeaturedNote,omitempty"`

	ReceiveAnnouncementEmail bool `json:"receiveAnnouncementEmail,omitempty"`

	AlwaysMarkNsfw bool `json:"alwaysMarkNsfw,omitempty"`

	PinnedPageId *string `json:"pinnedPageId,omitempty"`

	MutedWords [][]string `json:"mutedWords,omitempty"`

	MutedInstances []string `json:"mutedInstances,omitempty"`

	MutingNotificationTypes []string `json:"mutingNotificationTypes,omitempty"`

	EmailNotificationTypes []string `json:"emailNotificationTypes,omitempty"`
}
