/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse2003Properties struct {
	Width float32 `json:"width"`

	Height float32 `json:"height"`

	AvgColor string `json:"avgColor,omitempty"`
}
