/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20020Local struct {
	TotalCount []float32 `json:"totalCount"`

	TotalSize []float32 `json:"totalSize"`

	IncCount []float32 `json:"incCount"`

	IncSize []float32 `json:"incSize"`

	DecCount []float32 `json:"decCount"`

	DecSize []float32 `json:"decSize"`
}
