/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineObject184 struct {
	Body string `json:"body"`

	Header *string `json:"header,omitempty"`

	Icon *string `json:"icon,omitempty"`
}
