/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type InlineResponse20042 struct {
	IsFavorited bool `json:"isFavorited"`

	IsWatching bool `json:"isWatching"`

	IsMutedThread bool `json:"isMutedThread"`
}
