/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type Page struct {
	Id string `json:"id"`

	CreatedAt time.Time `json:"createdAt"`

	UpdatedAt time.Time `json:"updatedAt"`

	Title string `json:"title"`

	Name string `json:"name"`

	Summary *string `json:"summary"`

	Content Array `json:"content"`

	Variables Array `json:"variables"`

	UserId string `json:"userId"`

	User User `json:"user"`
}
