/*
 * Misskey API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: v1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method string
	// Pattern is the pattern of the URI.
	Pattern string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// Routes is the list of the generated Route.
type Routes []Route

// NewRouter returns a new router.
func NewRouter() *gin.Engine {
	router := gin.Default()
	for _, route := range routes {
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Index is the index handler.
func Index(c *gin.Context) {
	c.String(http.StatusOK, "Hello World!")
}

var routes = Routes{
	{
		"Index",
		http.MethodGet,
		"/api/",
		Index,
	},

	{
		"BlockingCreate",
		http.MethodPost,
		"/api/blocking/create",
		BlockingCreate,
	},

	{
		"BlockingDelete",
		http.MethodPost,
		"/api/blocking/delete",
		BlockingDelete,
	},

	{
		"BlockingList",
		http.MethodPost,
		"/api/blocking/list",
		BlockingList,
	},

	{
		"ClipsAddNote",
		http.MethodPost,
		"/api/clips/add-note",
		ClipsAddNote,
	},

	{
		"ClipsNotes",
		http.MethodPost,
		"/api/clips/notes",
		ClipsNotes,
	},

	{
		"I",
		http.MethodPost,
		"/api/i",
		I,
	},

	{
		"IFavorites",
		http.MethodPost,
		"/api/i/favorites",
		IFavorites,
	},

	{
		"IGalleryLikes",
		http.MethodPost,
		"/api/i/gallery/likes",
		IGalleryLikes,
	},

	{
		"IGalleryPosts",
		http.MethodPost,
		"/api/i/gallery/posts",
		IGalleryPosts,
	},

	{
		"IGetWordMutedNotesCount",
		http.MethodPost,
		"/api/i/get-word-muted-notes-count",
		IGetWordMutedNotesCount,
	},

	{
		"INotifications",
		http.MethodPost,
		"/api/i/notifications",
		INotifications,
	},

	{
		"IPageLikes",
		http.MethodPost,
		"/api/i/page-likes",
		IPageLikes,
	},

	{
		"IPages",
		http.MethodPost,
		"/api/i/pages",
		IPages,
	},

	{
		"IPin",
		http.MethodPost,
		"/api/i/pin",
		IPin,
	},

	{
		"IReadAllMessagingMessages",
		http.MethodPost,
		"/api/i/read-all-messaging-messages",
		IReadAllMessagingMessages,
	},

	{
		"IReadAllUnreadNotes",
		http.MethodPost,
		"/api/i/read-all-unread-notes",
		IReadAllUnreadNotes,
	},

	{
		"IReadAnnouncement",
		http.MethodPost,
		"/api/i/read-announcement",
		IReadAnnouncement,
	},

	{
		"IUnpin",
		http.MethodPost,
		"/api/i/unpin",
		IUnpin,
	},

	{
		"IUpdate",
		http.MethodPost,
		"/api/i/update",
		IUpdate,
	},

	{
		"IUserGroupInvites",
		http.MethodPost,
		"/api/i/user-group-invites",
		IUserGroupInvites,
	},

	{
		"MuteCreate",
		http.MethodPost,
		"/api/mute/create",
		MuteCreate,
	},

	{
		"MuteDelete",
		http.MethodPost,
		"/api/mute/delete",
		MuteDelete,
	},

	{
		"MuteList",
		http.MethodPost,
		"/api/mute/list",
		MuteList,
	},

	{
		"MyApps",
		http.MethodPost,
		"/api/my/apps",
		MyApps,
	},

	{
		"SwRegister",
		http.MethodPost,
		"/api/sw/register",
		SwRegister,
	},

	{
		"SwUnregister",
		http.MethodPost,
		"/api/sw/unregister",
		SwUnregister,
	},

	{
		"AdminAbuseUserReports",
		http.MethodPost,
		"/api/admin/abuse-user-reports",
		AdminAbuseUserReports,
	},

	{
		"AdminAccountsCreate",
		http.MethodPost,
		"/api/admin/accounts/create",
		AdminAccountsCreate,
	},

	{
		"AdminAccountsDelete",
		http.MethodPost,
		"/api/admin/accounts/delete",
		AdminAccountsDelete,
	},

	{
		"AdminAdCreate",
		http.MethodPost,
		"/api/admin/ad/create",
		AdminAdCreate,
	},

	{
		"AdminAdDelete",
		http.MethodPost,
		"/api/admin/ad/delete",
		AdminAdDelete,
	},

	{
		"AdminAdList",
		http.MethodPost,
		"/api/admin/ad/list",
		AdminAdList,
	},

	{
		"AdminAdUpdate",
		http.MethodPost,
		"/api/admin/ad/update",
		AdminAdUpdate,
	},

	{
		"AdminAnnouncementsCreate",
		http.MethodPost,
		"/api/admin/announcements/create",
		AdminAnnouncementsCreate,
	},

	{
		"AdminAnnouncementsDelete",
		http.MethodPost,
		"/api/admin/announcements/delete",
		AdminAnnouncementsDelete,
	},

	{
		"AdminAnnouncementsList",
		http.MethodPost,
		"/api/admin/announcements/list",
		AdminAnnouncementsList,
	},

	{
		"AdminAnnouncementsUpdate",
		http.MethodPost,
		"/api/admin/announcements/update",
		AdminAnnouncementsUpdate,
	},

	{
		"AdminDeleteAllFilesOfAUser",
		http.MethodPost,
		"/api/admin/delete-all-files-of-a-user",
		AdminDeleteAllFilesOfAUser,
	},

	{
		"AdminDeleteLogs",
		http.MethodPost,
		"/api/admin/delete-logs",
		AdminDeleteLogs,
	},

	{
		"AdminDriveCleanRemoteFiles",
		http.MethodPost,
		"/api/admin/drive/clean-remote-files",
		AdminDriveCleanRemoteFiles,
	},

	{
		"AdminDriveCleanup",
		http.MethodPost,
		"/api/admin/drive/cleanup",
		AdminDriveCleanup,
	},

	{
		"AdminDriveFiles",
		http.MethodPost,
		"/api/admin/drive/files",
		AdminDriveFiles,
	},

	{
		"AdminDriveShowFile",
		http.MethodPost,
		"/api/admin/drive/show-file",
		AdminDriveShowFile,
	},

	{
		"AdminEmojiAdd",
		http.MethodPost,
		"/api/admin/emoji/add",
		AdminEmojiAdd,
	},

	{
		"AdminEmojiCopy",
		http.MethodPost,
		"/api/admin/emoji/copy",
		AdminEmojiCopy,
	},

	{
		"AdminEmojiList",
		http.MethodPost,
		"/api/admin/emoji/list",
		AdminEmojiList,
	},

	{
		"AdminEmojiListRemote",
		http.MethodPost,
		"/api/admin/emoji/list-remote",
		AdminEmojiListRemote,
	},

	{
		"AdminEmojiRemove",
		http.MethodPost,
		"/api/admin/emoji/remove",
		AdminEmojiRemove,
	},

	{
		"AdminEmojiUpdate",
		http.MethodPost,
		"/api/admin/emoji/update",
		AdminEmojiUpdate,
	},

	{
		"AdminFederationDeleteAllFiles",
		http.MethodPost,
		"/api/admin/federation/delete-all-files",
		AdminFederationDeleteAllFiles,
	},

	{
		"AdminFederationRefreshRemoteInstanceMetadata",
		http.MethodPost,
		"/api/admin/federation/refresh-remote-instance-metadata",
		AdminFederationRefreshRemoteInstanceMetadata,
	},

	{
		"AdminFederationRemoveAllFollowing",
		http.MethodPost,
		"/api/admin/federation/remove-all-following",
		AdminFederationRemoveAllFollowing,
	},

	{
		"AdminFederationUpdateInstance",
		http.MethodPost,
		"/api/admin/federation/update-instance",
		AdminFederationUpdateInstance,
	},

	{
		"AdminGetIndexStats",
		http.MethodPost,
		"/api/admin/get-index-stats",
		AdminGetIndexStats,
	},

	{
		"AdminGetTableStats",
		http.MethodPost,
		"/api/admin/get-table-stats",
		AdminGetTableStats,
	},

	{
		"AdminInvite",
		http.MethodPost,
		"/api/admin/invite",
		AdminInvite,
	},

	{
		"AdminModeratorsAdd",
		http.MethodPost,
		"/api/admin/moderators/add",
		AdminModeratorsAdd,
	},

	{
		"AdminModeratorsRemove",
		http.MethodPost,
		"/api/admin/moderators/remove",
		AdminModeratorsRemove,
	},

	{
		"AdminPromoCreate",
		http.MethodPost,
		"/api/admin/promo/create",
		AdminPromoCreate,
	},

	{
		"AdminQueueClear",
		http.MethodPost,
		"/api/admin/queue/clear",
		AdminQueueClear,
	},

	{
		"AdminQueueDeliverDelayed",
		http.MethodPost,
		"/api/admin/queue/deliver-delayed",
		AdminQueueDeliverDelayed,
	},

	{
		"AdminQueueInboxDelayed",
		http.MethodPost,
		"/api/admin/queue/inbox-delayed",
		AdminQueueInboxDelayed,
	},

	{
		"AdminQueueJobs",
		http.MethodPost,
		"/api/admin/queue/jobs",
		AdminQueueJobs,
	},

	{
		"AdminQueueStats",
		http.MethodPost,
		"/api/admin/queue/stats",
		AdminQueueStats,
	},

	{
		"AdminRelaysAdd",
		http.MethodPost,
		"/api/admin/relays/add",
		AdminRelaysAdd,
	},

	{
		"AdminRelaysList",
		http.MethodPost,
		"/api/admin/relays/list",
		AdminRelaysList,
	},

	{
		"AdminRelaysRemove",
		http.MethodPost,
		"/api/admin/relays/remove",
		AdminRelaysRemove,
	},

	{
		"AdminResetPassword",
		http.MethodPost,
		"/api/admin/reset-password",
		AdminResetPassword,
	},

	{
		"AdminResolveAbuseUserReport",
		http.MethodPost,
		"/api/admin/resolve-abuse-user-report",
		AdminResolveAbuseUserReport,
	},

	{
		"AdminResyncChart",
		http.MethodPost,
		"/api/admin/resync-chart",
		AdminResyncChart,
	},

	{
		"AdminSendEmail",
		http.MethodPost,
		"/api/admin/send-email",
		AdminSendEmail,
	},

	{
		"AdminServerInfo",
		http.MethodPost,
		"/api/admin/server-info",
		AdminServerInfo,
	},

	{
		"AdminShowModerationLogs",
		http.MethodPost,
		"/api/admin/show-moderation-logs",
		AdminShowModerationLogs,
	},

	{
		"AdminShowUser",
		http.MethodPost,
		"/api/admin/show-user",
		AdminShowUser,
	},

	{
		"AdminShowUsers",
		http.MethodPost,
		"/api/admin/show-users",
		AdminShowUsers,
	},

	{
		"AdminSilenceUser",
		http.MethodPost,
		"/api/admin/silence-user",
		AdminSilenceUser,
	},

	{
		"AdminSuspendUser",
		http.MethodPost,
		"/api/admin/suspend-user",
		AdminSuspendUser,
	},

	{
		"AdminUnsilenceUser",
		http.MethodPost,
		"/api/admin/unsilence-user",
		AdminUnsilenceUser,
	},

	{
		"AdminUnsuspendUser",
		http.MethodPost,
		"/api/admin/unsuspend-user",
		AdminUnsuspendUser,
	},

	{
		"AdminUpdateMeta",
		http.MethodPost,
		"/api/admin/update-meta",
		AdminUpdateMeta,
	},

	{
		"AdminVacuum",
		http.MethodPost,
		"/api/admin/vacuum",
		AdminVacuum,
	},

	{
		"AntennasCreate",
		http.MethodPost,
		"/api/antennas/create",
		AntennasCreate,
	},

	{
		"AntennasDelete",
		http.MethodPost,
		"/api/antennas/delete",
		AntennasDelete,
	},

	{
		"AntennasList",
		http.MethodPost,
		"/api/antennas/list",
		AntennasList,
	},

	{
		"AntennasNotes",
		http.MethodPost,
		"/api/antennas/notes",
		AntennasNotes,
	},

	{
		"AntennasShow",
		http.MethodPost,
		"/api/antennas/show",
		AntennasShow,
	},

	{
		"AntennasUpdate",
		http.MethodPost,
		"/api/antennas/update",
		AntennasUpdate,
	},

	{
		"AppCreate",
		http.MethodPost,
		"/api/app/create",
		AppCreate,
	},

	{
		"AppShow",
		http.MethodPost,
		"/api/app/show",
		AppShow,
	},

	{
		"AuthSessionGenerate",
		http.MethodPost,
		"/api/auth/session/generate",
		AuthSessionGenerate,
	},

	{
		"AuthSessionShow",
		http.MethodPost,
		"/api/auth/session/show",
		AuthSessionShow,
	},

	{
		"AuthSessionUserkey",
		http.MethodPost,
		"/api/auth/session/userkey",
		AuthSessionUserkey,
	},

	{
		"ChannelsCreate",
		http.MethodPost,
		"/api/channels/create",
		ChannelsCreate,
	},

	{
		"ChannelsFeatured",
		http.MethodPost,
		"/api/channels/featured",
		ChannelsFeatured,
	},

	{
		"ChannelsFollow",
		http.MethodPost,
		"/api/channels/follow",
		ChannelsFollow,
	},

	{
		"ChannelsFollowed",
		http.MethodPost,
		"/api/channels/followed",
		ChannelsFollowed,
	},

	{
		"ChannelsOwned",
		http.MethodPost,
		"/api/channels/owned",
		ChannelsOwned,
	},

	{
		"ChannelsShow",
		http.MethodPost,
		"/api/channels/show",
		ChannelsShow,
	},

	{
		"ChannelsUnfollow",
		http.MethodPost,
		"/api/channels/unfollow",
		ChannelsUnfollow,
	},

	{
		"ChannelsUpdate",
		http.MethodPost,
		"/api/channels/update",
		ChannelsUpdate,
	},

	{
		"ChartsActiveUsers",
		http.MethodPost,
		"/api/charts/active-users",
		ChartsActiveUsers,
	},

	{
		"ChartsDrive",
		http.MethodPost,
		"/api/charts/drive",
		ChartsDrive,
	},

	{
		"ChartsFederation",
		http.MethodPost,
		"/api/charts/federation",
		ChartsFederation,
	},

	{
		"ChartsHashtag",
		http.MethodPost,
		"/api/charts/hashtag",
		ChartsHashtag,
	},

	{
		"ChartsInstance",
		http.MethodPost,
		"/api/charts/instance",
		ChartsInstance,
	},

	{
		"ChartsNetwork",
		http.MethodPost,
		"/api/charts/network",
		ChartsNetwork,
	},

	{
		"ChartsNotes",
		http.MethodPost,
		"/api/charts/notes",
		ChartsNotes,
	},

	{
		"ChartsUserDrive",
		http.MethodPost,
		"/api/charts/user/drive",
		ChartsUserDrive,
	},

	{
		"ChartsUserFollowing",
		http.MethodPost,
		"/api/charts/user/following",
		ChartsUserFollowing,
	},

	{
		"ChartsUserNotes",
		http.MethodPost,
		"/api/charts/user/notes",
		ChartsUserNotes,
	},

	{
		"ChartsUserReactions",
		http.MethodPost,
		"/api/charts/user/reactions",
		ChartsUserReactions,
	},

	{
		"ChartsUsers",
		http.MethodPost,
		"/api/charts/users",
		ChartsUsers,
	},

	{
		"ClipsCreate",
		http.MethodPost,
		"/api/clips/create",
		ClipsCreate,
	},

	{
		"ClipsDelete",
		http.MethodPost,
		"/api/clips/delete",
		ClipsDelete,
	},

	{
		"ClipsList",
		http.MethodPost,
		"/api/clips/list",
		ClipsList,
	},

	{
		"ClipsShow",
		http.MethodPost,
		"/api/clips/show",
		ClipsShow,
	},

	{
		"ClipsUpdate",
		http.MethodPost,
		"/api/clips/update",
		ClipsUpdate,
	},

	{
		"NotesClips",
		http.MethodPost,
		"/api/notes/clips",
		NotesClips,
	},

	{
		"ChannelsPinNote",
		http.MethodPost,
		"/api/channels/pin-note",
		ChannelsPinNote,
	},

	{
		"RequestResetPassword",
		http.MethodPost,
		"/api/request-reset-password",
		RequestResetPassword,
	},

	{
		"ResetDb",
		http.MethodPost,
		"/api/reset-db",
		ResetDb,
	},

	{
		"ResetPassword",
		http.MethodPost,
		"/api/reset-password",
		ResetPassword,
	},

	{
		"Drive",
		http.MethodPost,
		"/api/drive",
		Drive,
	},

	{
		"DriveFiles",
		http.MethodPost,
		"/api/drive/files",
		DriveFiles,
	},

	{
		"DriveFilesAttachedNotes",
		http.MethodPost,
		"/api/drive/files/attached-notes",
		DriveFilesAttachedNotes,
	},

	{
		"DriveFilesCheckExistence",
		http.MethodPost,
		"/api/drive/files/check-existence",
		DriveFilesCheckExistence,
	},

	{
		"DriveFilesCreate",
		http.MethodPost,
		"/api/drive/files/create",
		DriveFilesCreate,
	},

	{
		"DriveFilesDelete",
		http.MethodPost,
		"/api/drive/files/delete",
		DriveFilesDelete,
	},

	{
		"DriveFilesFind",
		http.MethodPost,
		"/api/drive/files/find",
		DriveFilesFind,
	},

	{
		"DriveFilesFindByHash",
		http.MethodPost,
		"/api/drive/files/find-by-hash",
		DriveFilesFindByHash,
	},

	{
		"DriveFilesShow",
		http.MethodPost,
		"/api/drive/files/show",
		DriveFilesShow,
	},

	{
		"DriveFilesUpdate",
		http.MethodPost,
		"/api/drive/files/update",
		DriveFilesUpdate,
	},

	{
		"DriveFilesUploadFromUrl",
		http.MethodPost,
		"/api/drive/files/upload-from-url",
		DriveFilesUploadFromUrl,
	},

	{
		"DriveFolders",
		http.MethodPost,
		"/api/drive/folders",
		DriveFolders,
	},

	{
		"DriveFoldersCreate",
		http.MethodPost,
		"/api/drive/folders/create",
		DriveFoldersCreate,
	},

	{
		"DriveFoldersDelete",
		http.MethodPost,
		"/api/drive/folders/delete",
		DriveFoldersDelete,
	},

	{
		"DriveFoldersFind",
		http.MethodPost,
		"/api/drive/folders/find",
		DriveFoldersFind,
	},

	{
		"DriveFoldersShow",
		http.MethodPost,
		"/api/drive/folders/show",
		DriveFoldersShow,
	},

	{
		"DriveFoldersUpdate",
		http.MethodPost,
		"/api/drive/folders/update",
		DriveFoldersUpdate,
	},

	{
		"DriveStream",
		http.MethodPost,
		"/api/drive/stream",
		DriveStream,
	},

	{
		"ApGet",
		http.MethodPost,
		"/api/ap/get",
		ApGet,
	},

	{
		"ApShow",
		http.MethodPost,
		"/api/ap/show",
		ApShow,
	},

	{
		"FederationDns",
		http.MethodPost,
		"/api/federation/dns",
		FederationDns,
	},

	{
		"FederationFollowers",
		http.MethodPost,
		"/api/federation/followers",
		FederationFollowers,
	},

	{
		"FederationFollowing",
		http.MethodPost,
		"/api/federation/following",
		FederationFollowing,
	},

	{
		"FederationInstances",
		http.MethodPost,
		"/api/federation/instances",
		FederationInstances,
	},

	{
		"FederationShowInstance",
		http.MethodPost,
		"/api/federation/show-instance",
		FederationShowInstance,
	},

	{
		"FederationUpdateRemoteUser",
		http.MethodPost,
		"/api/federation/update-remote-user",
		FederationUpdateRemoteUser,
	},

	{
		"FederationUsers",
		http.MethodPost,
		"/api/federation/users",
		FederationUsers,
	},

	{
		"FollowingCreate",
		http.MethodPost,
		"/api/following/create",
		FollowingCreate,
	},

	{
		"FollowingDelete",
		http.MethodPost,
		"/api/following/delete",
		FollowingDelete,
	},

	{
		"FollowingInvalidate",
		http.MethodPost,
		"/api/following/invalidate",
		FollowingInvalidate,
	},

	{
		"FollowingRequestsAccept",
		http.MethodPost,
		"/api/following/requests/accept",
		FollowingRequestsAccept,
	},

	{
		"FollowingRequestsCancel",
		http.MethodPost,
		"/api/following/requests/cancel",
		FollowingRequestsCancel,
	},

	{
		"FollowingRequestsList",
		http.MethodPost,
		"/api/following/requests/list",
		FollowingRequestsList,
	},

	{
		"FollowingRequestsReject",
		http.MethodPost,
		"/api/following/requests/reject",
		FollowingRequestsReject,
	},

	{
		"GalleryFeatured",
		http.MethodPost,
		"/api/gallery/featured",
		GalleryFeatured,
	},

	{
		"GalleryPopular",
		http.MethodPost,
		"/api/gallery/popular",
		GalleryPopular,
	},

	{
		"GalleryPosts",
		http.MethodPost,
		"/api/gallery/posts",
		GalleryPosts,
	},

	{
		"GalleryPostsCreate",
		http.MethodPost,
		"/api/gallery/posts/create",
		GalleryPostsCreate,
	},

	{
		"GalleryPostsDelete",
		http.MethodPost,
		"/api/gallery/posts/delete",
		GalleryPostsDelete,
	},

	{
		"GalleryPostsLike",
		http.MethodPost,
		"/api/gallery/posts/like",
		GalleryPostsLike,
	},

	{
		"GalleryPostsShow",
		http.MethodPost,
		"/api/gallery/posts/show",
		GalleryPostsShow,
	},

	{
		"GalleryPostsUnlike",
		http.MethodPost,
		"/api/gallery/posts/unlike",
		GalleryPostsUnlike,
	},

	{
		"GalleryPostsUpdate",
		http.MethodPost,
		"/api/gallery/posts/update",
		GalleryPostsUpdate,
	},

	{
		"GamesReversiGames",
		http.MethodPost,
		"/api/games/reversi/games",
		GamesReversiGames,
	},

	{
		"GamesReversiGamesShow",
		http.MethodPost,
		"/api/games/reversi/games/show",
		GamesReversiGamesShow,
	},

	{
		"GamesReversiGamesSurrender",
		http.MethodPost,
		"/api/games/reversi/games/surrender",
		GamesReversiGamesSurrender,
	},

	{
		"GamesReversiInvitations",
		http.MethodPost,
		"/api/games/reversi/invitations",
		GamesReversiInvitations,
	},

	{
		"GamesReversiMatch",
		http.MethodPost,
		"/api/games/reversi/match",
		GamesReversiMatch,
	},

	{
		"GamesReversiMatchCancel",
		http.MethodPost,
		"/api/games/reversi/match/cancel",
		GamesReversiMatchCancel,
	},

	{
		"UsersGroupsCreate",
		http.MethodPost,
		"/api/users/groups/create",
		UsersGroupsCreate,
	},

	{
		"UsersGroupsDelete",
		http.MethodPost,
		"/api/users/groups/delete",
		UsersGroupsDelete,
	},

	{
		"UsersGroupsInvitationsAccept",
		http.MethodPost,
		"/api/users/groups/invitations/accept",
		UsersGroupsInvitationsAccept,
	},

	{
		"UsersGroupsInvitationsReject",
		http.MethodPost,
		"/api/users/groups/invitations/reject",
		UsersGroupsInvitationsReject,
	},

	{
		"UsersGroupsInvite",
		http.MethodPost,
		"/api/users/groups/invite",
		UsersGroupsInvite,
	},

	{
		"UsersGroupsJoined",
		http.MethodPost,
		"/api/users/groups/joined",
		UsersGroupsJoined,
	},

	{
		"UsersGroupsLeave",
		http.MethodPost,
		"/api/users/groups/leave",
		UsersGroupsLeave,
	},

	{
		"UsersGroupsOwned",
		http.MethodPost,
		"/api/users/groups/owned",
		UsersGroupsOwned,
	},

	{
		"UsersGroupsPull",
		http.MethodPost,
		"/api/users/groups/pull",
		UsersGroupsPull,
	},

	{
		"UsersGroupsShow",
		http.MethodPost,
		"/api/users/groups/show",
		UsersGroupsShow,
	},

	{
		"UsersGroupsTransfer",
		http.MethodPost,
		"/api/users/groups/transfer",
		UsersGroupsTransfer,
	},

	{
		"UsersGroupsUpdate",
		http.MethodPost,
		"/api/users/groups/update",
		UsersGroupsUpdate,
	},

	{
		"HashtagsList",
		http.MethodPost,
		"/api/hashtags/list",
		HashtagsList,
	},

	{
		"HashtagsSearch",
		http.MethodPost,
		"/api/hashtags/search",
		HashtagsSearch,
	},

	{
		"HashtagsShow",
		http.MethodPost,
		"/api/hashtags/show",
		HashtagsShow,
	},

	{
		"HashtagsTrend",
		http.MethodPost,
		"/api/hashtags/trend",
		HashtagsTrend,
	},

	{
		"HashtagsUsers",
		http.MethodPost,
		"/api/hashtags/users",
		HashtagsUsers,
	},

	{
		"UsersListsCreate",
		http.MethodPost,
		"/api/users/lists/create",
		UsersListsCreate,
	},

	{
		"UsersListsDelete",
		http.MethodPost,
		"/api/users/lists/delete",
		UsersListsDelete,
	},

	{
		"UsersListsList",
		http.MethodPost,
		"/api/users/lists/list",
		UsersListsList,
	},

	{
		"UsersListsPull",
		http.MethodPost,
		"/api/users/lists/pull",
		UsersListsPull,
	},

	{
		"UsersListsPush",
		http.MethodPost,
		"/api/users/lists/push",
		UsersListsPush,
	},

	{
		"UsersListsShow",
		http.MethodPost,
		"/api/users/lists/show",
		UsersListsShow,
	},

	{
		"UsersListsUpdate",
		http.MethodPost,
		"/api/users/lists/update",
		UsersListsUpdate,
	},

	{
		"MessagingHistory",
		http.MethodPost,
		"/api/messaging/history",
		MessagingHistory,
	},

	{
		"MessagingMessages",
		http.MethodPost,
		"/api/messaging/messages",
		MessagingMessages,
	},

	{
		"MessagingMessagesCreate",
		http.MethodPost,
		"/api/messaging/messages/create",
		MessagingMessagesCreate,
	},

	{
		"MessagingMessagesDelete",
		http.MethodPost,
		"/api/messaging/messages/delete",
		MessagingMessagesDelete,
	},

	{
		"MessagingMessagesRead",
		http.MethodPost,
		"/api/messaging/messages/read",
		MessagingMessagesRead,
	},

	{
		"Announcements",
		http.MethodPost,
		"/api/announcements",
		Announcements,
	},

	{
		"Endpoint",
		http.MethodPost,
		"/api/endpoint",
		Endpoint,
	},

	{
		"Endpoints",
		http.MethodPost,
		"/api/endpoints",
		Endpoints,
	},

	{
		"GetOnlineUsersCount",
		http.MethodPost,
		"/api/get-online-users-count",
		GetOnlineUsersCount,
	},

	{
		"Meta",
		http.MethodPost,
		"/api/meta",
		Meta,
	},

	{
		"Ping",
		http.MethodPost,
		"/api/ping",
		Ping,
	},

	{
		"ServerInfo",
		http.MethodPost,
		"/api/server-info",
		ServerInfo,
	},

	{
		"Stats",
		http.MethodPost,
		"/api/stats",
		Stats,
	},

	{
		"ChannelsTimeline",
		http.MethodPost,
		"/api/channels/timeline",
		ChannelsTimeline,
	},

	{
		"Notes",
		http.MethodPost,
		"/api/notes",
		Notes,
	},

	{
		"NotesChildren",
		http.MethodPost,
		"/api/notes/children",
		NotesChildren,
	},

	{
		"NotesConversation",
		http.MethodPost,
		"/api/notes/conversation",
		NotesConversation,
	},

	{
		"NotesCreate",
		http.MethodPost,
		"/api/notes/create",
		NotesCreate,
	},

	{
		"NotesDelete",
		http.MethodPost,
		"/api/notes/delete",
		NotesDelete,
	},

	{
		"NotesFavoritesCreate",
		http.MethodPost,
		"/api/notes/favorites/create",
		NotesFavoritesCreate,
	},

	{
		"NotesFavoritesDelete",
		http.MethodPost,
		"/api/notes/favorites/delete",
		NotesFavoritesDelete,
	},

	{
		"NotesFeatured",
		http.MethodPost,
		"/api/notes/featured",
		NotesFeatured,
	},

	{
		"NotesGlobalTimeline",
		http.MethodPost,
		"/api/notes/global-timeline",
		NotesGlobalTimeline,
	},

	{
		"NotesHybridTimeline",
		http.MethodPost,
		"/api/notes/hybrid-timeline",
		NotesHybridTimeline,
	},

	{
		"NotesLocalTimeline",
		http.MethodPost,
		"/api/notes/local-timeline",
		NotesLocalTimeline,
	},

	{
		"NotesMentions",
		http.MethodPost,
		"/api/notes/mentions",
		NotesMentions,
	},

	{
		"NotesPollsRecommendation",
		http.MethodPost,
		"/api/notes/polls/recommendation",
		NotesPollsRecommendation,
	},

	{
		"NotesPollsVote",
		http.MethodPost,
		"/api/notes/polls/vote",
		NotesPollsVote,
	},

	{
		"NotesReactions",
		http.MethodPost,
		"/api/notes/reactions",
		NotesReactions,
	},

	{
		"NotesRenotes",
		http.MethodPost,
		"/api/notes/renotes",
		NotesRenotes,
	},

	{
		"NotesReplies",
		http.MethodPost,
		"/api/notes/replies",
		NotesReplies,
	},

	{
		"NotesSearch",
		http.MethodPost,
		"/api/notes/search",
		NotesSearch,
	},

	{
		"NotesSearchByTag",
		http.MethodPost,
		"/api/notes/search-by-tag",
		NotesSearchByTag,
	},

	{
		"NotesShow",
		http.MethodPost,
		"/api/notes/show",
		NotesShow,
	},

	{
		"NotesState",
		http.MethodPost,
		"/api/notes/state",
		NotesState,
	},

	{
		"NotesThreadMutingCreate",
		http.MethodPost,
		"/api/notes/thread-muting/create",
		NotesThreadMutingCreate,
	},

	{
		"NotesThreadMutingDelete",
		http.MethodPost,
		"/api/notes/thread-muting/delete",
		NotesThreadMutingDelete,
	},

	{
		"NotesTimeline",
		http.MethodPost,
		"/api/notes/timeline",
		NotesTimeline,
	},

	{
		"NotesTranslate",
		http.MethodPost,
		"/api/notes/translate",
		NotesTranslate,
	},

	{
		"NotesUnrenote",
		http.MethodPost,
		"/api/notes/unrenote",
		NotesUnrenote,
	},

	{
		"NotesUserListTimeline",
		http.MethodPost,
		"/api/notes/user-list-timeline",
		NotesUserListTimeline,
	},

	{
		"NotesWatchingCreate",
		http.MethodPost,
		"/api/notes/watching/create",
		NotesWatchingCreate,
	},

	{
		"NotesWatchingDelete",
		http.MethodPost,
		"/api/notes/watching/delete",
		NotesWatchingDelete,
	},

	{
		"PromoRead",
		http.MethodPost,
		"/api/promo/read",
		PromoRead,
	},

	{
		"NotificationsCreate",
		http.MethodPost,
		"/api/notifications/create",
		NotificationsCreate,
	},

	{
		"NotificationsMarkAllAsRead",
		http.MethodPost,
		"/api/notifications/mark-all-as-read",
		NotificationsMarkAllAsRead,
	},

	{
		"NotificationsRead",
		http.MethodPost,
		"/api/notifications/read",
		NotificationsRead,
	},

	{
		"PagesCreate",
		http.MethodPost,
		"/api/pages/create",
		PagesCreate,
	},

	{
		"PagesDelete",
		http.MethodPost,
		"/api/pages/delete",
		PagesDelete,
	},

	{
		"PagesFeatured",
		http.MethodPost,
		"/api/pages/featured",
		PagesFeatured,
	},

	{
		"PagesLike",
		http.MethodPost,
		"/api/pages/like",
		PagesLike,
	},

	{
		"PagesShow",
		http.MethodPost,
		"/api/pages/show",
		PagesShow,
	},

	{
		"PagesUnlike",
		http.MethodPost,
		"/api/pages/unlike",
		PagesUnlike,
	},

	{
		"PagesUpdate",
		http.MethodPost,
		"/api/pages/update",
		PagesUpdate,
	},

	{
		"NotesReactionsCreate",
		http.MethodPost,
		"/api/notes/reactions/create",
		NotesReactionsCreate,
	},

	{
		"NotesReactionsDelete",
		http.MethodPost,
		"/api/notes/reactions/delete",
		NotesReactionsDelete,
	},

	{
		"RoomShow",
		http.MethodPost,
		"/api/room/show",
		RoomShow,
	},

	{
		"RoomUpdate",
		http.MethodPost,
		"/api/room/update",
		RoomUpdate,
	},

	{
		"EmailAddressAvailable",
		http.MethodPost,
		"/api/email-address/available",
		EmailAddressAvailable,
	},

	{
		"PinnedUsers",
		http.MethodPost,
		"/api/pinned-users",
		PinnedUsers,
	},

	{
		"UsernameAvailable",
		http.MethodPost,
		"/api/username/available",
		UsernameAvailable,
	},

	{
		"Users",
		http.MethodPost,
		"/api/users",
		Users,
	},

	{
		"UsersClips",
		http.MethodPost,
		"/api/users/clips",
		UsersClips,
	},

	{
		"UsersFollowers",
		http.MethodPost,
		"/api/users/followers",
		UsersFollowers,
	},

	{
		"UsersFollowing",
		http.MethodPost,
		"/api/users/following",
		UsersFollowing,
	},

	{
		"UsersGalleryPosts",
		http.MethodPost,
		"/api/users/gallery/posts",
		UsersGalleryPosts,
	},

	{
		"UsersGetFrequentlyRepliedUsers",
		http.MethodPost,
		"/api/users/get-frequently-replied-users",
		UsersGetFrequentlyRepliedUsers,
	},

	{
		"UsersNotes",
		http.MethodPost,
		"/api/users/notes",
		UsersNotes,
	},

	{
		"UsersPages",
		http.MethodPost,
		"/api/users/pages",
		UsersPages,
	},

	{
		"UsersReactions",
		http.MethodPost,
		"/api/users/reactions",
		UsersReactions,
	},

	{
		"UsersRecommendation",
		http.MethodPost,
		"/api/users/recommendation",
		UsersRecommendation,
	},

	{
		"UsersRelation",
		http.MethodPost,
		"/api/users/relation",
		UsersRelation,
	},

	{
		"UsersReportAbuse",
		http.MethodPost,
		"/api/users/report-abuse",
		UsersReportAbuse,
	},

	{
		"UsersSearch",
		http.MethodPost,
		"/api/users/search",
		UsersSearch,
	},

	{
		"UsersSearchByUsernameAndHost",
		http.MethodPost,
		"/api/users/search-by-username-and-host",
		UsersSearchByUsernameAndHost,
	},

	{
		"UsersShow",
		http.MethodPost,
		"/api/users/show",
		UsersShow,
	},

	{
		"UsersStats",
		http.MethodPost,
		"/api/users/stats",
		UsersStats,
	},
}
